// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMUiUR1sRa1PvS19U7m2LPgGwwjVolL9I',
    appId: '1:23885517471:web:d25734a079ab7085ff08aa',
    messagingSenderId: '23885517471',
    projectId: 'loginapp-b3a2a',
    authDomain: 'loginapp-b3a2a.firebaseapp.com',
    storageBucket: 'loginapp-b3a2a.firebasestorage.app',
    measurementId: 'G-LQSFSGPX4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL3Wz7AK8Iw6Zgqr1W5IYv2G1lh1IVm-s',
    appId: '1:23885517471:android:c9259e87f7d00c0fff08aa',
    messagingSenderId: '23885517471',
    projectId: 'loginapp-b3a2a',
    storageBucket: 'loginapp-b3a2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPaBWKk6-vw3PAVtTT5TJlpmnQI0LnXmg',
    appId: '1:23885517471:ios:2c3549c77e213c5bff08aa',
    messagingSenderId: '23885517471',
    projectId: 'loginapp-b3a2a',
    storageBucket: 'loginapp-b3a2a.firebasestorage.app',
    iosBundleId: 'com.example.logionapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPaBWKk6-vw3PAVtTT5TJlpmnQI0LnXmg',
    appId: '1:23885517471:ios:2c3549c77e213c5bff08aa',
    messagingSenderId: '23885517471',
    projectId: 'loginapp-b3a2a',
    storageBucket: 'loginapp-b3a2a.firebasestorage.app',
    iosBundleId: 'com.example.logionapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMUiUR1sRa1PvS19U7m2LPgGwwjVolL9I',
    appId: '1:23885517471:web:ca986c3789574a95ff08aa',
    messagingSenderId: '23885517471',
    projectId: 'loginapp-b3a2a',
    authDomain: 'loginapp-b3a2a.firebaseapp.com',
    storageBucket: 'loginapp-b3a2a.firebasestorage.app',
    measurementId: 'G-N8XERT4J0W',
  );
}
